myname = input("What's her name? ")
myLunch = input("What is she having for lunch? ")
print(myname, "is going to be chowing down on", myLunch, "very soon!")
number = input("Give me a number: ")
group = input("Give me a collective noun for a group of things: ")

print("No I don't think that", number, "is a", group)
print()
yourName = input("Name: ")
whatYear = input("What year is it?: ")
print(yourName, "thinks it is", whatYear)
print("=== Your Song Generator ===")
print("""You'll be asked a bunch of questions""")
print("then we'll make you up an amazing")
print("song, totally copyright free 😭")
